const nameOfYourFavoriteMovie = ;
const theNameOfTheApplicationInWhichYouSpendTheMostTime = ;
const theAddressOfTheArticleAboutJavascriptInWikipedia = ;
const LoremipsumdolorsitametconsecteturadipisicingelitRepellendusrepellatvoluptatemPorrodolorumcupiditateaperiamrepellendusrerumfugitmaximeistevoluptateculpaquodoloreenimdebitisiustodoloremqueeiuserror = ;

console.log(nameOfYourFavoriteMovie);
console.log(theNameOfTheApplicationInWhichYouSpendTheMostTime);
console.log(theAddressOfTheArticleAboutJavascriptInWikipedia);
console.log(LoremipsumdolorsitametconsecteturadipisicingelitRepellendusrepellatvoluptatemPorrodolorumcupiditateaperiamrepellendusrerumfugitmaximeistevoluptateculpaquodoloreenimdebitisiustodoloremqueeiuserror);
